@baseURL = http://localhost:3000/

GET {{baseURL}}

###
# @name create account
POST {{baseURL}}accounts
content-type: application/json

{
  "name": "John Doe",
  "email": "john.doe465@gmail.com",
  "password": "123456"
}

###
# @name create session
POST {{baseURL}}sessions
content-type: application/json

{
  "email": "john.doe465@gmail.com",
  "password": "123456"
}
